In [1]:
pip install tensorflow


In [22]:
import tensorflow as tf

In [23]:
from tensorflow.keras.preprocessing.text import one_hot

In [24]:
sentences = [
    'I absolutely love this product; it works perfectly.',
    'I absolutely love wonderful and productive day.',
    'The movie was fantastic and full of excitement.',
    'I am feeling very happy and grateful right now.',
    'This is the best decision I have ever made.'
]

In [25]:
sentences

['I absolutely love this product; it works perfectly.',
 'I absolutely love wonderful and productive day.',
 'The movie was fantastic and full of excitement.',
 'I am feeling very happy and grateful right now.',
 'This is the best decision I have ever made.']

In [26]:
vocabulary_size = 10000

In [27]:
one_hot_representation = [one_hot(words, vocabulary_size)for words in sentences]

In [28]:
one_hot_representation

[[3051, 1601, 8111, 581, 2891, 8558, 4217, 4677],
 [3051, 1601, 8111, 3304, 9459, 2888, 8528],
 [4200, 1024, 5023, 8646, 9459, 9225, 218, 5524],
 [3051, 1933, 210, 6073, 8294, 9459, 4631, 2164, 1011],
 [581, 6705, 4200, 7719, 2859, 3051, 8308, 7977, 6874]]

In [37]:
## word embeding representation
from tensorflow.keras.layers import Embedding, Input
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np


In [30]:
## make all sentences same size
sent_size = 10
embed_docs = pad_sequences(one_hot_representation, padding='post', maxlen=sent_size)

In [31]:
embed_docs

array([[3051, 1601, 8111,  581, 2891, 8558, 4217, 4677,    0,    0],
       [3051, 1601, 8111, 3304, 9459, 2888, 8528,    0,    0,    0],
       [4200, 1024, 5023, 8646, 9459, 9225,  218, 5524,    0,    0],
       [3051, 1933,  210, 6073, 8294, 9459, 4631, 2164, 1011,    0],
       [ 581, 6705, 4200, 7719, 2859, 3051, 8308, 7977, 6874,    0]],
      dtype=int32)

In [38]:
dimensions = 10
model = Sequential()
model.add(Input(shape=(sent_size,)))
model.add(Embedding(
    input_dim=vocabulary_size,
    output_dim=dimensions
))
model.compile(optimizer='adam', loss='mse')

In [39]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 10, 10)         │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [40]:
model.predict(embed_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step


array([[[-0.00899589, -0.01982139, -0.00790082, -0.00425444,
          0.03562759,  0.01144391,  0.02902478, -0.00599728,
         -0.04106998, -0.00522669],
        [-0.00268428, -0.04020426, -0.04807472, -0.01741754,
          0.04171577, -0.03632804, -0.03283707,  0.02010567,
          0.01875878, -0.04090143],
        [-0.0113079 , -0.00017347, -0.04131521,  0.01552216,
          0.00430105, -0.02070848,  0.00196033, -0.01898569,
          0.00728865, -0.00250588],
        [ 0.03527161, -0.04624493,  0.00541432, -0.01094879,
          0.0340916 ,  0.03919064, -0.01817535, -0.04724659,
          0.01956079, -0.00832423],
        [ 0.00729633,  0.03831026, -0.02035241,  0.03959804,
         -0.02098508, -0.0172594 , -0.01403322,  0.00389081,
         -0.01303577, -0.03461177],
        [-0.03010618, -0.04908603, -0.04982219, -0.00670551,
          0.00089331, -0.00728496, -0.01858027, -0.00641496,
          0.01710126,  0.04368946],
        [-0.00674   ,  0.01453852, -0.02192495,  0.0

In [43]:
embed_docs[0]

array([3051, 1601, 8111,  581, 2891, 8558, 4217, 4677,    0,    0],
      dtype=int32)